apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:latest
        ports:
        - containerPort: 8080
        env:
        - name: NIFI_WEB_HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nifi
